name: travel_app
description: Plataforma de Solicitação de Viagens Corporativas
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # Para enviar dados via webhook
  intl: ^0.18.0 # Para formatação de datas
  flutter_svg: ^2.0.6 # Para ícones, se precisar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
